config/routes.rb
Rails.application.routes.draw do
    root "rooms#index"

    # resources :rooms
    # resources :questions

    # post "/questions/new", to: "questions#create"

    resources :rooms do
      resources :questions
    end

    resources :questions, only: [:create]

    resources :questions do
      member do
        post 'upvote'
        put :upvote
      end
    end

    get "questions/:id/upvote", to: "questions#upvote"
end

app/models/question.rb
class Question < ActiveRecord::Base
    default_scope {order('-score')}
    belongs_to :room
end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :questions
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name,  presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, length: { maximum: 255 }, 
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
	end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    def new
    	@question = Question.new
    end
  
    def create
        @room_id = params[:id]
        @question = Question.new(question_params)
        puts @question.save
        redirect_to :back
    end
  
    def upvote
        @question = Question.find(params[:question_id])
    	@question.score += 1
        @question.save
        redirect_to :back
    end
  
    private
        
    def question_params
        params.require(:question).permit(:body, :room_id)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    def index
        @rooms = Room.all
    end

    def show
        @room = Room.find(params[:id])
        @question = @room.questions.build
    end

    def create
        @room = Room.new(room_params)

        if @room.save
            redirect_to @room
        else
            flash[:error] = @room.errors.full_messages
            render "new"
        end
    end

    def new
        @room = Room.new
    end

    def edit
        @room = Room.find(params[:id])
    end

    def update
        @room = Room.find(params[:id])
        @room.update(room_params)
    end

    def destroy
        room = Room.find(params[:id])
        room.destroy

        redirect_to "/rooms"
    end

    private
        
    def room_params
        params.require(:room).permit(:name, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Quirk</title>
        <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport'>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>
        <nav class="navbar">
            <div class="container">
                <a href="/" class="title">QUIRK</a>
            </div>
        </nav>

        <%= yield %>

    </body>
</html>

app/views/pages/home.html.erb
<h1>Find the best credit <br> card for you.</h1>

app/views/questions/new.html.erb
<h1>Ask a question!</h1>

<%= form_for @question do |f| %>
    Ask here: <%= f.text_field :body %>
    <%= f.submit %>
<% end %>

app/views/rooms/home.html.erb
<h1>List of rooms</h1>

<a href="/new">Create a new room</a>

<% @rooms.each do |r| %>
    <p> <%= r.name %> </p> 
    <p> <%= r.description %> </p>
<% end %>

app/views/rooms/index.html.erb
<div class="container">
    <div class="title"><h1>Rooms near you</h1></div>

    <div class="list-container">
        <% @rooms.each do |r| %>
            <%= link_to room_path(r), :class => "room row" do %>
                <div class="id col-md-1 col-sm-1 col-xs-1"><%= r.id %></div>
                <div class="name col-md-3 col-sm-3 col-xs-11"><%= r.name %></div>

                <div class="description col-md-8 col-sm-8 col-xs-11"><%= r.description %></div>
            <% end %>
            <hr>
        <% end %>
        <a href="/rooms/new" class="room row new-room">
            <div class="col-md-12">Create a new room</div>
        </a>
    </div>
</div>

app/views/rooms/new.html.erb
<div class="container new-room">
    <h1>Create new room</h1>

    <% if flash[:error] %>
        <p><%= flash[:error][0] %>!</p>
    <% end %>

    <%= form_for @room do |f| %>
        <div class="text-field-container">Name: 
            <div class="text-field"><%= f.text_field :name %></div>
        </div>
        <div class="text-field-container">Description: 
            <div class="text-field"><%= f.text_field :description %></div>
        </div>
        <%= f.submit%>
    <% end %>
</div>

app/views/rooms/show.html.erb
<div class="container">
    <div class="title">
        <h1 id="room-name"><%= @room.name %></h1>
        <h3 id="room-description"><%= @room.description %></h3>
        <div class="status">
            <div class="indicator indicator-live"></div>
            <div class="indicator-status"></div>
        </div>
    </div>
    <br>

    <%= form_for @question, html: { autocomplete: 'off' } do |q| %>
        <div><%= q.text_field :body, :placeholder => "Have a question? Ask here!", :class => "text-field" %></div>
        <%= q.hidden_field :room_id %>
        <%= q.submit "Ask Question", :class => "submit-btn"%>
    <% end %>
    <div class="list-container">
        <hr class="ask-hr">
        <% @room.questions.each do |q| %>
            <div class="question">
                <div class="score">
                    <%= link_to '+ ' + q.score.to_s, :controller => "questions", :action => "upvote", :question_id => q.id, method: :post %>
                </div>
                    <%= q.body %>
            </div>
            <hr>
        <% end %>
    </div>
    <%=  link_to "Delete room", room_path(@room), method: :delete %>

</div>